# Generated by Django 5.0.7 on 2024-08-04 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Пример: Дома, В парке",
                        max_length=150,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "start_date",
                    models.TimeField(
                        blank=True,
                        help_text="(формат 13:31) не обязательное поле",
                        null=True,
                        verbose_name="Дата начала",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Пример: Прогулка, Чтение",
                        max_length=200,
                        verbose_name="Описание действия, составляющего привычку",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="True (если это приятная привычка), False (если это полезная привычка)",
                        verbose_name="Указывает, является ли привычка приятной (вознаграждением)",
                    ),
                ),
                (
                    "frequency",
                    models.SmallIntegerField(
                        help_text="Пример: 1 (ежедневно), 7 (раз в неделю).",
                        verbose_name="Периодичность выполнения привычки в днях.",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Кусочек торта, Просмотр фильма",
                        max_length=200,
                        null=True,
                        verbose_name="писание вознаграждения за выполнение полезной привычки",
                    ),
                ),
                (
                    "duration",
                    models.SmallIntegerField(
                        help_text="Пример: 60 (максимальное значение — 120 секунд)",
                        verbose_name="Предполагаемое время на выполнение привычки в секундах",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="True (публичная), False (частная)",
                        verbose_name="Указывает на публичность привычки (может ли она быть видна другим пользователям)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Укажите дату создания",
                        null=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Укажите дату изменения",
                        null=True,
                        verbose_name="Дата изменения",
                    ),
                ),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Прогулка может быть связана с 'Чтением книги' как вознаграждение.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Ссылка на другую привычку, которая связана с текущей (только для полезных привычек)",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
