# Generated by Django 5.0.7 on 2024-08-07 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_linked_habit_habit_reward"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habitconnection",
            name="linked_habit",
        ),
        migrations.RemoveField(
            model_name="habitconnection",
            name="reward",
        ),
        migrations.AddField(
            model_name="habitconnection",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="habitconnection",
            name="habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habits.habit",
                verbose_name="связь с привычкой",
            ),
        ),
        migrations.AddField(
            model_name="habitconnection",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="связь с пользователем",
            ),
        ),
    ]
